# Generated by Django 3.1.7 on 2021-06-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='balance',
            new_name='amount',
        ),
    ]
